import sys
import random

# The purpose of this script is to make a test FASTA file of 16S long contigs to check for evidence of chimeric ends. The 
# bacteria chosen are based on Zymo's 16S microbial control standards, which we can run as part of a process QC to look for 
# evidence of chimeric molecules created as an unintended side-effect (by too many PCR cycles, bad reagents, etc.). The 16S
# gene in bacteria is appox 1500 bp composed of 9 variable regions that are unique to a genus or species. What we produce 
# here is a mock file of assembled short into long reads or native long reads for the full 16S gene. The mock file can be 
# used to test the accuracy of the "hunter script", and to see how a process faliure can lead to changes in truncated or 
# chimeric molcueles. In this mock file, we control how many contigs we check, how the diferent bacteria are mixed (at what
# ratios), what fraction will be chimeric, and which fraction will be truncated. Contigs that are too short (truncated) will
# be missing the end(s) so we can't test for chimeric end if those ends are missing. Likewise, if a contig was not a perfect 
# match to the "left end" and "right end" anchor sequences, we will report that contig as "undefined" even if full length.
# All of these "modes" are possible from real samples in a real libraray prep and sequencing event.
#
# Considerations: user parameters for fraction chimeric, truncated, and undefined, must be numbers from 0 up to 100. Any 
# value above or below will be auto-adjusted. The sum of those values must be <= 100. If they are above, each value will 
# be scaled uniformly to become sum == 100. The minumum number of contigs = 100.

# the full length 16S from Zymo, as decribed in their documentation.
Bacillus_V1V9 = "TTTATCGGAGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGGACAGATGGGAGCTTGCTCCCTGATGTTAGCGGCGGACGGGTGAGTAACACGTGGGTAACCTGCCTGTAAGACTGGGATAACTCCGGGAAACCGGGGCTAATACCGGATGCTTGTTTGAACCGCATGGTTCAAACATAAAAGGTGGCTTCGGCTACCACTTACAGATGGACCCGCGGCGCATTAGCTAGTTGGTGAGGTAATGGCTCACCAAGGCAACGATGCGTAGCCGACCTGAGAGGGTGATCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAGCTCTGTTGTTAGGGAAGAACAAGTACCGTTCGAATAGGGCGGTACCTTGACGGTACCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGGGCTCGCAGGCGGTTCCTTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTCTCTGGTCTGTAACTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAAGTGTTAGGGGGTTTCCGCCCCTTAGTGCTGCAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGGTCGCAAGACTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCCTCTGACAATCCTAGAGATAGGACGTCCCCTTCGGGGGCAGAGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTGATCTTAGTTGCCAGCATTCAGTTGGGCACTCTAAGGTGACTGCCGGTGACAAACCGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTGCTACAATGGACAGAACAAAGGGCAGCGAAACCGCGAGGTTAAGCCAATCCCACAAATCTGTTCTCAGTTCGGATCGCAGTCTGCAACTCGACTGCGTGAAGCTGGAATCGCTAGTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCACGAGAGTTTGTAACACCCGAAGTCGGTGAGGTAACCTTTTAGGAGCCAGCCGCCGAAGGTGGGACAGATGATTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTCCTTTCTAAGGA"

Enterococcus_V1V9 = "TTATGAGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAACGCTTCTTTCCTCCCGAGTGCTTGCACTCATTTGGAAAGAGGAGTGGCGGACGGGTGAGTAACACGTGGGTAACCTACCCATCAGAGGGGGATAACACTTGGAAACAGGTGCTAATACCGCATAACAGTTTATGCCGCATGGCATAAGAGTGAAAGGCGCTTTCGGGTGTCACTGATGGATGGACCCGCGGTGCATTAGCTAGTTGGTGAGGTAACGGCTCACCAAGGCCACGATGCATAGCCGACCTGAGAGGGTGATCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCGGCAATGGACGAAAGTCTGACCGAGCAACGCCGCGTGAGTGAAGAAGGTTTTCGGATCGTAAAACTCTGTTGTTAGAGAAGAACAAGGACGTTAGTAACTGAACGTCCCCTGACGGTATCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGGAGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGCTCTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAAGTGTTGGAGGGTTTCCGCCCTTCAGTGCTGCAGCAAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCCTTTGACCACTCTAGAGATAGAGCTTTCCCTTCGGGGACAAAGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATTGTTAGTTGCCATCATTTAGTTGGGCACTCTAGCGAGACTGCCGGTGACAAACCGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTGCTACAATGGGAAGTACAACGAGTCGCTAGACCGCGAGGTCATGCAAATCTCTTAAAGCTTCTCTCAGTTCGGATTGCAGGCTGCAACTCGCCTGCATGAAGCCGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCACGAGAGTTTGTAACACCCGAAGTCGGTGAGGTAACCTTTTTGGAGCCAGCCGCCTAAGGTGGGATAGATGATTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTCCTTTCTA"

Escherichia_V1V9 = "AAATTGAAGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAACGGTAACAGGAAGAAGCTTGCTTCTTTGCTGACGAGTGGCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGAGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCAAGACCAAAGAGGGGGACCTTCGGGCCTCTTGCCATCGGATGTGCCCAGATGGGATTAGCTAGTAGGTGGGGTAACGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACAGAACTTTCCAGAGATGGATTGGTGCCTTCGGGAACTGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAACCGTAGGGGAACCTGCGGTTGGATCACCTCCTTA"

Lactobacillus_V1V9 = "AGAGTTTGATCCTGGCTCAGGATGAACGCCGGCGGTGTGCCTAATACATGCAAGTCGAACGCGTTGGCCCAATTGATTGATGGTGCTTGCACCTGATTGATTTTGGTCGCCAACGAGTGGCGGACGGGTGAGTAACACGTAGGTAACCTGCCCAGAAGCGGGGGACAACATTTGGAAACAGATGCTAATACCGCATAACAACGTTGTTCGCATGAACAACGCTTAAAAGATGGCTTCTCGCTATCACTTCTGGATGGACCTGCGGTGCATTAGCTTGTTGGTGGGGTAACGGCCTACCAAGGCGATGATGCATAGCCGAGTTGAGAGACTGATCGGCCACAATGGGACTGAGACACGGCCCATACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCACAATGGGCGCAAGCCTGATGGAGCAACACCGCGTGAGTGAAGAAGGGTTTCGGCTCGTAAAGCTCTGTTGTTAAAGAAGAACACGTATGAGAGTAACTGTTCATACGTTGACGGTATTTAACCAGAAAGTCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGATTTATTGGGCGTAAAGAGAGTGCAGGCGGTTTTCTAAGTCTGATGTGAAAGCCTTCGGCTTAACCGGAGAAGTGCATCGGAAACTGGATAACTTGAGTGCAGAAGAGGGTAGTGGAACTCCATGTGTAGCGGTGGAATGCGTAGATATATGGAAGAACACCAGTGGCGAAGGCGGCTACCTGGTCTGCAACTGACGCTGAGACTCGAAAGCATGGGTAGCGAACAGGATTAGATACCCTGGTAGTCCATGCCGTAAACGATGAGTGCTAGGTGTTGGAGGGTTTCCGCCCTTCAGTGCCGGAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCTACGCGAAGAACCTTACCAGGTCTTGACATCTTGCGCCAACCCTAGAGATAGGGCGTTTCCTTCGGGAACGCAATGACAGGTGGTGCATGGTCGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTGTTACTAGTTGCCAGCATTAAGTTGGGCACTCTAGTGAGACTGCCGGTGACAAACCGGAGGAAGGTGGGGACGACGTCAGATCATCATGCCCCTTATGACCTGGGCTACACACGTGCTACAATGGACGGTACAACGAGTCGCGAACTCGCGAGGGCAAGCAAATCTCTTAAAACCGTTCTCAGTTCGGACTGCAGGCTGCAACTCGCCTGCACGAAGTCGGAATCGCTAGTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGAGAGTTTGTAACACCCAAAGTCGGTGGGGTAACCTTTTAGGAGCCAGCCGCCTAAGGTGGGACAGATGATTAGGGTGAAGTCGTAACAAGGTAGCCGTAGGAGAACCTGCGGCTGGATCACCTCCTT"

Listeria_V1V9 = "TTTAAAGAGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAACGAACGGAGGAAGAGCTTGCTCTTCCAAAGTTAGTGGCGGACGGGTGAGTAACACGTGGGCAACCTGCCTGTAAGTTGGGGATAACTCCGGGAAACCGGGGCTAATACCGAATGATAAAGTGTGGCGCATGCCACGCTTTTGAAAGATGGTTTCGGCTATCGCTTACAGATGGGCCCGCGGTGCATTAGCTAGTTGGTAGGGTAATGGCCTACCAAGGCAACGATGCATAGCCGACCTGAGAGGGTGATCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGTATGAAGAAGGTTTTCGGATCGTAAAGTACTGTTGTTAGAGAAGAACAAGGATAAGAGTAACTGCTTGTCCCTTGACGGTATCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGCGCGCAGGCGGTCTTTTAAGTCTGATGTGAAAGCCCCCGGCTTAACCGGGGAGGGTCATTGGAAACTGGAAGACTGGAGTGCAGAAGAGGAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGATATGTGGAGGAACACCAGTGGCGAAGGCGACTCTCTGGTCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAAGTGTTAGGGGGTTTCCGCCCCTTAGTGCTGCAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCCTTTGACCACTCTGGAGACAGAGCTTTCCCTTCGGGGACAAAGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTGATTTTAGTTGCCAGCATTTAGTTGGGCACTCTAAAGTGACTGCCGGTGCAAGCCGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTGCTACAATGGATAGTACAAAGGGTCGCGAAGCCGCGAGGTGGAGCTAATCCCATAAAACTATTCTCAGTTCGGATTGTAGGCTGCAACTCGCCTACATGAAGCCGGAATCGCTAGTAATCGTGGATCAGCATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCACGAGAGTTTGTAACACCCGAAGTCGGTAGGGTAACCTTTATGGAGCCAGCCGCCGAAGGTGGGACAGATAATTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTCCTTTCT"

Pseudomonas_V1V9 = "AGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGATGAAGGGAGCTTGCTCCTGGATTCAGCGGCGGACGGGTGAGTAATGCCTAGGAATCTGCCTGGTAGTGGGGGATAACGTCCGGAAACGGGCGCTAATACCGCATACGTCCTGAGGGAGAAAGTGGGGGATCTTCGGACCTCACGCTATCAGATGAGCCTAGGTCGGATTAGCTAGTTGGTGGGGTAAAGGCCTACCAAGGCGACGATCCGTAACTGGTCTGAGAGGATGATCAGTCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGCCATGCCGCGTGTGTGAAGAAGGTCTTCGGATTGTAAAGCACTTTAAGTTGGGAGGAAGGGCAGTAAGTTAATACCTTGCTGTTTTGACGTTACCAACAGAATAAGCACCGGCTAACTTCGTGCCAGCAGCCGCGGTAATACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCAGCAAGTTGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTACTGAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTGTGTAGCGGTGAAATGCGTAGATATAGGAAGGAACACCAGTGGCGAAGGCGACCACCTGGACTGATACTGACACTGAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTAGCCGTTGGGATCCTTGAGATCTTAGTGGCGCAGCTAACGCGATAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCTGGCCTTGACATGCTGAGAACTTTCCAGAGATGGATTGGTGCCTTCGGGAACTCAGACACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGTAACGAGCGCAACCCTTGTCCTTAGTTACCAGCACCTCGGGTGGGCACTCTAAGGAGACTGCCGGTGACAAACCGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGGCCAGGGCTACACACGTGCTACAATGGTCGGTACAAAGGGTTGCCAAGCCGCGAGGTGGAGCTAATCCCATAAAACCGATCGTAGTCCGGATCGCAGTCTGCAACTCGACTGCGTGAAGTCGGAATCGCTAGTAATCGTGAATCAGAATGTCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCTCCAGAAGTAGCTAGTCTAACCGCAAGGGGGACGGTTACCACGGAGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGCTGGATCACCTCCTT"

Salmonella_V1V9 = "AGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAACGGTAACAGGAAGCAGCTTGCTGCTTTGCTGACGACCTCCCCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTGGCTAATACCGCATAACGTCGCAAGACCAAAGAGGGGGACCTTCGGGCCTCTTACCATCAGATGTGCCCAGATGGGATTAGCTTGTTGGTGAGGTAACGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGTGTTGTGGTTAATAACCGCAGCAATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTCGAAACTGGCAGGCTTGAGTCTTGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTAGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGATTAGGTCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTAGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTTGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAACCGTAGGGGAACCTGCGGTTGGATCACCTCCTT"

Staphylococcus_V1V9 = "TTTTATGGAGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAACGGACGAGAAGCTTGCTTCTCTGATGTTAGCGGCGGACGGGTGAGTAACACGTGGATAACCTACCTATAAGACTGGGATAACTTCGGGAAACCGGAGCTAATACCGGATAATATTTTGAACCGCATGGTTCAAAAGTGAAAGACGGTCTTGCTGTCACTTATAGATGGATCCGCGCTGCATTAGCTAGTTGGTAAGGTAACGGCTTACCAAGGCAACGATGCATAGCCGACCTGAGAGGGTGATCGGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTCTTCGGATCGTAAAACTCTGTTATTAGGGAAGAACATATGTGTAAGTAACTGTGCACATCTTGACGGTACCTAATCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAAGTGTTAGGGGGTTTCCGCCCCTTAGTGCTGCAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGACCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAAATCTTGACATCCTTTGACAACTCTAGAGATAGAGCCTTCCCCTTCGGGGGACAAAGTGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTAAGCTTAGTTGCCATCATTAAGTTGGGCACTCTAAGTTGACTGCCGGTGACAAACCGGAGGAAGGTGGGGATGACGTCAAATCATCATGCCCCTTATGATTTGGGCTACACACGTGCTACAATGGACAATACAAAGGGCAGCGAAACCGCGAGGTCAAGCAAATCCCATAAAGTTGTTCTCAGTTCGGATTGTAGTCTGCAACTCGACTACATGAAGCTGGAATCGCTAGTAATCGTAGATCAGCATGCTACGGTGAATACGTTCCCGGGTCTTGTACACACCGCCCGTCACACCACGAGAGTTTGTAACACCCGAAGCCGGTGGAGTAACCTTTTAGGAGCTAGCCGTCGAAGGTGGGACAAATGATTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTCCTTTCTA"

# a random sequence used to approx. a contig that has no matches, such as noise, off target contig, or of poor read quality and thus many errors.
unknown_contig = "ATGCTGGCCGTCGGTCCAGAGAGCTTTGTCACTCCACGATAGATCGTGACGATGTGATAGACAGCAGTAGTCGTGCGATGACTACTGGATAGCATGCTCGATATCGATGCGATGCTCTAGTGAGCGTAGTGTCGTCGCAGATCGTAGCGTAGTCGTGCGATCGATCGTAGCTAGCTAGCTAGCTAGCGCTGCGATGCGTCAGATCGTGCATCATCGATGCTAGCTAGCTAGCTAGCTGATCGTAGCGCTAGCTAGCTGCGTAGCGTAGTCGTAGTCGTAGTGATCGATCGGATCGACGATCGACGATCGATCAGCTAGCTAGTCGATCATCGTAGCTGATCGACGATCGTACGTAGCTGATCGCGCGCGTCGCTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGCTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCGATCGTAGCTAGCTAGCTACGATGCTGCGATGCGCGATCGATCGTAGCGATCGATCGTAGCGATCGTAGTAGCGTAGCTAGCTAGCGTAGCGTAGTCGATCGTAGCGTAGCTAGCTGATCGCTCGTCGTAGCTCGACGATCGTCGCAGCTCGTAGTCGTAGCGCTAGCTAGCTGATCG"

# -------------------------------------------

def create_contig_fasta(number, chimeric, trunc, unknown, code):
    try:
        # add all to dict - full seq as value with genus names as key
        contig_16_dict = {}
        contig_16_dict["Bacillus"] = Bacillus_V1V9
        contig_16_dict["Enterococcus"] = Enterococcus_V1V9
        contig_16_dict["Escherichia"] = Escherichia_V1V9
        contig_16_dict["Lactobacillus"] = Lactobacillus_V1V9
        contig_16_dict["Listeria"] = Listeria_V1V9
        contig_16_dict["Pseudomonas"] = Pseudomonas_V1V9
        contig_16_dict["Salmonella"] = Salmonella_V1V9
        contig_16_dict["Staphylococcus"] = Staphylococcus_V1V9

        contig_16_genus_list = []
        contig_16_genus_list.append("Bacillus")
        contig_16_genus_list.append("Enterococcus")
        contig_16_genus_list.append("Escherichia")
        contig_16_genus_list.append("Lactobacillus")
        contig_16_genus_list.append("Listeria")
        contig_16_genus_list.append("Pseudomonas")
        contig_16_genus_list.append("Salmonella")
        contig_16_genus_list.append("Staphylococcus")        

        # these parameters are defined by the user to make a custom mock file, very clean or dirty as needed for testing the hunter script.
        # Must have at least 100 contigs to create.
        number_contigs = number if float(number) >= 100 else 100       
        # these values must be between 0 and 100, as a percent value, not as fractional (0-1) value.
        percent_chimeric = chimeric if float(chimeric) >= 0 else 0     
        percent_truncated = trunc if float(trunc) >= 0 else 0     
        percent_undefined = unknown if float(unknown) >= 0 else 0

        if (float(percent_chimeric) > 100): percent_chimeric = 100
        if (float(percent_truncated) > 100): percent_truncated = 100
        if (float(percent_undefined) > 100): percent_undefined = 100
        # the code defines the weights given to the random picking of the 8 zymo genus. Is a one-letter code.
        distribution_code = code
        # adjust such that fractions not complete are <= 100.0
        sum_fractions = float(percent_chimeric) + float(percent_truncated) + float(percent_undefined)
        if(sum_fractions > 100):
            correction_factor = 100/sum_fractions            
            percent_chimeric = round(correction_factor * float(percent_chimeric))
            percent_truncated = round(correction_factor * float(percent_truncated))
            percent_undefined = round(correction_factor * float(percent_undefined))

        percent_complete = 100 - float(percent_chimeric) - float(percent_truncated) - float(percent_undefined)

        custom_output = "mock_contigs_" + str(number_contigs) + "_" + str(percent_chimeric) + "_" + str(percent_truncated) + "_" + str(percent_undefined) + "_" + distribution_code + ".fasta"
        output_file = open(custom_output, "w")
        # first split up the work into 4 parts, 1 for full length fraction, 1 for chimeric fraction, 1 for short fraction, 1 for undefined
        count_full = round(int(number_contigs) * float(percent_complete)/100)
        count_chimeric = round(int(number_contigs) * float(percent_chimeric)/100)
        count_truncated = round(int(number_contigs) * float(percent_truncated)/100)
        count_undefined = round(int(number_contigs) * float(percent_undefined)/100)
        # these function calls build each list of chosen complete contigs and if they are modified after
        create_full(contig_16_dict, contig_16_genus_list, count_full, distribution_code, output_file)
        create_chimeric(contig_16_dict, contig_16_genus_list, count_chimeric, distribution_code, output_file)
        create_truncated(contig_16_dict, contig_16_genus_list, count_truncated, distribution_code, output_file)
        create_undefined(count_undefined, output_file)
        output_file.close()

    except Exception as e:
        print("something very bad happened. Contact the creator.")
        exit ()

def create_full(contig_16_dict, contig_16_genus_list, how_many, distribution_type, output_file):
    # pick full seq randomly from the 16_list
    print("complete: " + str(how_many))
    for x_val in range(how_many):
        picked_genus = random_pick_weights(contig_16_genus_list, 1, distribution_type)[0]
        contig_name = ">full_" + str(x_val + 1) + "_" + picked_genus + "\n"
        output_file.write(contig_name)
        rnd_contig = contig_16_dict[picked_genus]  + "\n"
        output_file.write(rnd_contig)

def create_chimeric(contig_16_dict, contig_16_genus_list, how_many, distribution_type, output_file):
    # pick 2 contigs at random, and then cut in half and attach end of one to start of the other.
    print("chimeric: " + str(how_many))
    for x_val in range(how_many):
        picks = random_pick_weights(contig_16_genus_list, 2, distribution_type)
        left_genus = contig_16_dict[picks[0]]
        right_genus = contig_16_dict[picks[1]]        
        contig_name = ">chim_" + str(x_val + 1) + "_" + picks[0] + "_" + picks[1] + "\n"
        output_file.write(contig_name)
        # fixed cut and paste point for forming chimeras. Therefor, we cannot see chimeras that happen beyond this position.
        cut_point = 800
        chim_contig =  left_genus[:cut_point] + right_genus[cut_point:] + "\n"
        output_file.write(chim_contig)

def create_truncated(contig_16_dict, contig_16_genus_list, how_many, distribution_type, output_file): 
    # pick full seq randomly from the 16_list, but then trim X from the end of the contig
    print("truncated: " + str(how_many))
    for x_val in range(how_many):
        picked_genus = random_pick_weights(contig_16_genus_list, 1, distribution_type)[0]
        contig_name = ">trun_" + str(x_val + 1) + "_" + picked_genus + "\n"
        output_file.write(contig_name)
        # cut at random between 500 and 1100. Upper value chosen because right_end anchor for some genus are at 1200 bp mark, so
        # to be truncated we would need to remove those.
        cut_point = random.randint(500, 1100)
        rnd_contig =  contig_16_dict[picked_genus][:cut_point] + "\n"
        output_file.write(rnd_contig)

def create_undefined(how_many, output_file): 
    # is full length but no matching anchors on one or both ends. maybe noise?
    print("undefined: " + str(how_many))
    for x_val in range(how_many):
        contig_name = ">unkn_" + str(x_val + 1) + "_undefined" + "\n"
        output_file.write(contig_name)
        output_file.write(unknown_contig + "\n")

def random_pick_weights(contig_16_genus_list, to_return, distribution_code):
    # returns a list of results based on to_return value. default weight is uniform.
    weighted = [1,1,1,1,1,1,1,1]
    # these are the Zymo genus stored in the contig_16_genus_list
    #contig_16_genus_list.append("Bacillus")
    #contig_16_genus_list.append("Enterococcus")
    #contig_16_genus_list.append("Escherichia")
    #contig_16_genus_list.append("Lactobacillus")
    #contig_16_genus_list.append("Listeria")
    #contig_16_genus_list.append("Pseudomonas")
    #contig_16_genus_list.append("Salmonella")
    #contig_16_genus_list.append("Staphylococcus")        
    #
    # The distribution code picks a weight list, corresponding to each zymo genus. We are chooseing either 1 or 2
    # contigs to return from the list of weighted eight genus.
    #
    if distribution_code == "z": weighted = [12,15,9,22,15,6,10,10] # balanced control from zymo, 16S only
    if distribution_code == "s": weighted = [32,16,8,4,2,1,1,1] # a type of stagger of my creation
    if distribution_code == "t": weighted = [2,1,0,0,0,0,0,0] # a type of pick 2 only, not equal
    
    # list to store the randomly/weighted genus contigs for 16S, based on the number to return for this "type"
    # of contig (i.e. complete, chimeric, truncated...)
    return_genus_list = []
    for each_need in range(0,to_return):
        # get one 16S sequence for each contig needed, 1 or 2 in total
        found_it = False
        while not found_it:       
            # returns a list even when k=1
            random_pick = random.choices(contig_16_genus_list, weights = weighted, k = 1)[0]
            # make sure that what we picked is not already in the return list (without replacement aprrox.)
            if random_pick not in return_genus_list:
                return_genus_list.append(random_pick)
                found_it = True
                
    return(return_genus_list)
# -------------------------------------------
#
# MAIN LOOP

if (len(sys.argv) < 6):
    print ("Incorrect number of inputs. Requires: number of contigs, fraction chimeric, fraction trunc, fraction undefined, distribution code.")
    exit ()

number_contigs = sys.argv[1]
percent_chimeric = sys.argv[2]
percent_trunc = sys.argv[3]
percent_unknown = sys.argv[4]
distrib_code = sys.argv[5]
create_contig_fasta(number_contigs, percent_chimeric,  percent_trunc, percent_unknown, distrib_code)
